# ref: http://docs.travis-ci.com/user/build-configuration

language: cpp
compiler:
    - gcc

before_install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - g++-4.8
    - g++ --version
    - $(CXX) --version
    - wget "http://www.lua.org/ftp/lua-5.3.2.tar.gz" && tar xzf lua-5.3.2.tar.gz && cd lua-5.3.2 && sudo make linux test install;

install:
    - cd $TRAVIS_BUILD_DIR
    - make buildfbb
    - make all

script:
    - make test
