# ref: http://docs.travis-ci.com/user/build-configuration

language: cpp
sudo: required
compiler:
    - g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - sudo rm /usr/bin/g++
    - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
    - g++ --version
    - $(CXX) --version
    - wget "http://www.lua.org/ftp/lua-5.3.2.tar.gz" && tar xzf lua-5.3.2.tar.gz && cd lua-5.3.2 && sudo make linux test install;

install:
    - cd $TRAVIS_BUILD_DIR
    - make buildfbb
    - make all

script:
    - make test
